import { ThemeMeta } from './types';

export const THEME_CATALOG: ThemeMeta[] = [
  {
    id: 'betawi',
    name: 'Betawi Heritage',
    category: 'adat',
    subtitle: 'Adat Betawi Klasik Modern',
    description: 'Nuansa hangat adat Betawi berhias ornamen Gigi Balang, Ondel-ondel siluet elegan, dan arsitektur Rumah Kebaya.',
    thumbnail: '/assets/themes/betawi/thumbnail.jpg',
    previewColors: {
      primary: '#5B7065',
      secondary: '#B85D43',
      accent: '#D4AF37',
      bg: '#E8EBE3',
    },
    features: ['Gigi Balang Frame', 'Ondel-ondel Siluet', 'Bunga Flora Melayang', 'Musik Mengambang'],
    status: 'ready',
    favicon: '/assets/themes/betawi/favicon.svg',
  },
  {
    id: 'jawa',
    name: 'Javanese Royal Kraton',
    category: 'adat',
    subtitle: 'Adat Jawa Klasik Ningrat',
    description: 'Kemegahan ningrat keraton Jawa dengan ornamen sakral Gunungan Wayang Kulit, batik Parang, dan aksen emas keemasan.',
    thumbnail: '/assets/themes/jawa/thumbnail.svg',
    previewColors: {
      primary: '#1B3B2B',
      secondary: '#C5A059',
      accent: '#E5C158',
      bg: '#FAF8F2',
    },
    features: ['Gunungan Wayang Mas', 'Serat Ulem Pawiwahan', 'Bingkai Ukiran Keraton', 'Batik Royal Gold'],
    status: 'ready',
    favicon: '/assets/themes/jawa/favicon.svg',
  },
  {
    id: 'sunda',
    name: 'Sundanese Parahyangan',
    category: 'adat',
    subtitle: 'Adat Sunda Asri & Suci',
    description: 'Keanggunan mahkota Siger Sunda, ronce melati putih, motif Priangan, dan nuansa alam Parahyangan yang sejuk.',
    thumbnail: '/assets/themes/sunda/thumbnail.svg',
    previewColors: {
      primary: '#4A6B5D',
      secondary: '#E6D5B8',
      accent: '#D4AF37',
      bg: '#F4F7F4',
    },
    features: ['Mahkota Siger Sunda', 'Serat Ulem Pawiwahan', 'Ronce Melati Putih', 'Bambu Priangan Arch'],
    status: 'ready',
    favicon: '/assets/themes/sunda/favicon.svg',
  },
  {
    id: 'minimalist',
    name: 'Modern Botanical Minimalist',
    category: 'modern',
    subtitle: 'Nasional & Intimate Wedding',
    description: 'Gaya modern minimalis berbalut tipografi serif bersih, dedaunan eucalyptus cat air, dan tata letak lapang tanpa sekat.',
    thumbnail: '/assets/themes/minimalist/thumbnail.svg',
    previewColors: {
      primary: '#2D3748',
      secondary: '#9AA79C',
      accent: '#D4AF37',
      bg: '#F7FAFC',
    },
    features: ['Clean Aesthetic Serif', 'Eucalyptus Watercolor', 'Editorial Minimalist', 'Tata Letak Lapang'],
    status: 'ready',
    favicon: '/assets/themes/minimalist/favicon.svg',
  },
  {
    id: 'islamic',
    name: 'Islamic Arabian Garden',
    category: 'islami',
    subtitle: 'Syar\'i & Sakral Kontemporer',
    description: 'Nuansa sakral islami berhias lengkungan kubah Arabesque, kaligrafi bismillah, dan taburan bintang geometris.',
    thumbnail: '/assets/themes/islamic/thumbnail.svg',
    previewColors: {
      primary: '#0F4C5C',
      secondary: '#C5A059',
      accent: '#E5C158',
      bg: '#FAF6EE',
    },
    features: ['Arabesque Arches', 'Bismillah Kaligrafi', 'Islamic 8-Star Rub el Hizb', 'Syar\'i & Sakral Kontemporer'],
    status: 'ready',
    favicon: '/assets/themes/islamic/favicon.svg',
  },
  {
    id: 'minang',
    name: 'Minangkabau Royal Songket',
    category: 'adat',
    subtitle: 'Baralek Gadang Adat Minang',
    description: 'Kemegahan ranah Minang berhias mahkota Suntiang emas bertingkat, Rumah Gadang gonjong, ukiran Pucuak Rebung, dan beludru marun.',
    thumbnail: '/assets/themes/minang/thumbnail.svg',
    previewColors: {
      primary: '#7B1122',
      secondary: '#D4AF37',
      accent: '#FFF3C4',
      bg: '#FAF5F0',
    },
    features: ['Mahkota Suntiang Emas', 'Rumah Gadang Gonjong', 'Songket Pucuak Rebung', 'Baralek Gadang Minang'],
    status: 'ready',
    favicon: '/assets/themes/minang/favicon.svg',
  },
  {
    id: 'bali',
    name: 'Balinese Royal Temple',
    category: 'adat',
    subtitle: 'Pawiwahan Adat Bali Agung',
    description: 'Kemegahan sakral adat Bali berhias Gapura Candi Bentar, payung kehormatan Tedung Agung, ukiran Patra Punggel, dan keharuman Bunga Jepun Kamboja.',
    thumbnail: '/assets/themes/bali/thumbnail.svg',
    previewColors: {
      primary: '#7C2D12',
      secondary: '#C5A059',
      accent: '#E5C158',
      bg: '#FAF6F0',
    },
    features: ['Gapura Candi Bentar', 'Bunga Jepun Melayang', 'Tedung Agung Emas', 'Patra Punggel Carvings'],
    status: 'ready',
    favicon: '/assets/themes/bali/favicon.svg',
  },
  {
    id: 'batak',
    name: 'Batak Toba Royal Gorga',
    category: 'adat',
    subtitle: 'Unjuk Adat Bolon Batak Toba',
    description: 'Kemegahan adat Batak Toba berhias ornamen ukiran Gorga sakral, motif tenun Ulos Ragidup/Sadum, siluet Ruma Bolon, dan palet Tolu Bolit merah-hitam-emas.',
    thumbnail: '/assets/themes/batak/thumbnail.svg',
    previewColors: {
      primary: '#7A1B1E',
      secondary: '#1C1917',
      accent: '#D4AF37',
      bg: '#FAF6F0',
    },
    features: ['Ukiran Seni Gorga', 'Motif Ulos Ragidup', 'Siluet Ruma Bolon', 'Horas Jala Gabe'],
    status: 'ready',
    favicon: '/assets/themes/batak/favicon.svg',
  },
  {
    id: 'bugis',
    name: 'Bugis-Makassar Royal Baju Bodo',
    category: 'adat',
    subtitle: 'Baruga Saoraja & Sutra Lipa Sabbe',
    description: 'Kemegahan adat Bugis-Makassar berhias ornamen wadah Bosara renda emas, siluet atap Saoraja/Bola Soba, corak sutra Lipa Sabbe, dan aksara Lontara sakral.',
    thumbnail: '/assets/themes/bugis/thumbnail.svg',
    previewColors: {
      primary: '#8B1E1E',
      secondary: '#C59B27',
      accent: '#D97706',
      bg: '#FAF6F0',
    },
    features: ['Wadah Bosara Emas', 'Atap Saoraja Bangsawan', 'Taburan Bente & Pandan', 'Aksara Lontara Salama'],
    status: 'ready',
    favicon: '/assets/themes/bugis/favicon.svg',
  },
  {
    id: 'spotify',
    name: 'Spotify Interactive',
    category: 'modern',
    subtitle: 'Wedding Track & Love Playlist',
    description: 'Konsep viral pemutar musik Spotify dengan piringan hitam vinyl berputar, lencana Verified Newlyweds, dan album tracklist kisah cinta.',
    thumbnail: '/assets/themes/spotify/thumbnail.svg',
    previewColors: {
      primary: '#1DB954',
      secondary: '#181818',
      accent: '#1ED760',
      bg: '#121212',
    },
    features: ['Rotating Vinyl Cover', 'Verified Newlyweds', 'Album Tracklist', 'Floating Music Notes'],
    status: 'ready',
    favicon: '/assets/themes/spotify/favicon.svg',
  },
  {
    id: 'netflix',
    name: 'Netflix Premiere',
    category: 'modern',
    subtitle: 'Cinematic Wedding & Series',
    description: 'Konsep viral streaming sinematik Netflix dengan efek audio Ta-Dum!, episode Akad & Resepsi, rating 99% Match, serta profil bintang Cast & Crew.',
    thumbnail: '/assets/themes/netflix/thumbnail.svg',
    previewColors: {
      primary: '#E50914',
      secondary: '#141414',
      accent: '#FFFFFF',
      bg: '#0F0F0F',
    },
    features: ['Ta-Dum Sound Effect', 'Episode 1 & 2 Series', 'Cast & Crew Profile', 'Trending 99% Match'],
    status: 'ready',
    favicon: '/assets/themes/netflix/favicon.svg',
  },
  {
    id: 'apple',
    name: 'Apple iOS Bento Grid',
    category: 'modern',
    subtitle: 'Apple Ecosystem & Bento OS',
    description: 'Konsep modern viral iOS & Bento Grid dengan Dynamic Island interaktif, Face ID Lock Screen unlock audio, Apple Wallet gift cards, dan iMessage chat bubbles.',
    thumbnail: '/assets/themes/apple/thumbnail.svg',
    previewColors: {
      primary: '#007AFF',
      secondary: '#E5E5EA',
      accent: '#D4AF37',
      bg: '#F2F2F7',
    },
    features: ['Dynamic Island Widget', 'Lock Screen Unlock Chime', 'Bento Grid Layout', 'Apple Wallet Digital Gift'],
    status: 'ready',
    favicon: '/assets/themes/apple/favicon.svg',
  },
  {
    id: 'instagram',
    name: 'Instagram Stories & Reels',
    category: 'modern',
    subtitle: 'Wedding Stories & Close Friends',
    description: 'Konsep modern viral Instagram Stories berformat 9:16 vertikal imersif dengan progress bar tersegmentasi, stiker countdown live, RSVP polling, dan reaksi hati double-tap.',
    thumbnail: '/assets/themes/instagram/thumbnail.svg',
    previewColors: {
      primary: '#E1306C',
      secondary: '#FD1D1D',
      accent: '#FFD600',
      bg: '#000000',
    },
    features: ['Story Segmented Progress', 'Live Countdown Sticker', 'RSVP Poll Sticker', 'Double-Tap Floating Hearts'],
    status: 'ready',
    favicon: '/assets/themes/instagram/favicon.svg',
  },
];


