import { ThemeMeta } from './types';

export const THEME_CATALOG: ThemeMeta[] = [
  {
    id: 'betawi',
    name: 'Betawi Heritage',
    category: 'adat',
    subtitle: 'Adat Betawi Klasik Modern',
    description: 'Nuansa hangat adat Betawi berhias ornamen Gigi Balang, Ondel-ondel siluet elegan, dan arsitektur Rumah Kebaya.',
    thumbnail: '/assets/themes/betawi/thumbnail.jpg',
    previewColors: {
      primary: '#5B7065',
      secondary: '#B85D43',
      accent: '#D4AF37',
      bg: '#E8EBE3',
    },
    features: ['Gigi Balang Frame', 'Ondel-ondel Siluet', 'Bunga Flora Melayang', 'Musik Mengambang'],
    status: 'ready',
    favicon: '/assets/themes/betawi/favicon.svg',
  },
  {
    id: 'jawa',
    name: 'Javanese Royal Kraton',
    category: 'adat',
    subtitle: 'Adat Jawa Klasik Ningrat',
    description: 'Kemegahan ningrat keraton Jawa dengan ornamen sakral Gunungan Wayang Kulit, batik Parang, dan aksen emas keemasan.',
    thumbnail: '/assets/themes/jawa/thumbnail.svg',
    previewColors: {
      primary: '#1B3B2B',
      secondary: '#C5A059',
      accent: '#E5C158',
      bg: '#FAF8F2',
    },
    features: ['Gunungan Wayang Mas', 'Serat Ulem Pawiwahan', 'Bingkai Ukiran Keraton', 'Batik Royal Gold'],
    status: 'ready',
    favicon: '/assets/themes/jawa/favicon.svg',
  },
  {
    id: 'sunda',
    name: 'Sundanese Parahyangan',
    category: 'adat',
    subtitle: 'Adat Sunda Asri & Suci',
    description: 'Keanggunan mahkota Siger Sunda, ronce melati putih, motif Priangan, dan nuansa alam Parahyangan yang sejuk.',
    thumbnail: '/assets/themes/sunda/thumbnail.svg',
    previewColors: {
      primary: '#4A6B5D',
      secondary: '#E6D5B8',
      accent: '#D4AF37',
      bg: '#F4F7F4',
    },
    features: ['Mahkota Siger Sunda', 'Serat Ulem Pawiwahan', 'Ronce Melati Putih', 'Bambu Priangan Arch'],
    status: 'ready',
    favicon: '/assets/themes/sunda/favicon.svg',
  },
  {
    id: 'sunda_maroon',
    name: 'Sundanese Royal Maroon',
    category: 'adat',
    subtitle: 'Adat Sunda Elegan Beludru Maroon & Aksen Emas',
    description: 'Keanggunan mahkota Siger Sunda berbalut beludru merah maroon ningrat, ronce melati harum, sentuhan bahasa Indonesia yang santun, dan aksen emas berkilau.',
    thumbnail: '/assets/themes/sunda_maroon/thumbnail.svg',
    previewColors: {
      primary: '#7B1122',
      secondary: '#E6D5B8',
      accent: '#D4AF37',
      bg: '#FAF5F5',
    },
    features: ['Mahkota Siger Sunda Emas', 'Beludru Maroon & Gold', 'Wilujeng Sumping Siger', 'Gerbang Bambu Priangan'],
    status: 'ready',
    favicon: '/assets/themes/sunda_maroon/favicon.svg',
  },
  {
    id: 'minimalist',
    name: 'Modern Botanical Minimalist',
    category: 'modern',
    subtitle: 'Nasional & Intimate Wedding',
    description: 'Gaya modern minimalis berbalut tipografi serif bersih, dedaunan eucalyptus cat air, dan tata letak lapang tanpa sekat.',
    thumbnail: '/assets/themes/minimalist/thumbnail.svg',
    previewColors: {
      primary: '#2D3748',
      secondary: '#9AA79C',
      accent: '#D4AF37',
      bg: '#F7FAFC',
    },
    features: ['Clean Aesthetic Serif', 'Eucalyptus Watercolor', 'Editorial Minimalist', 'Tata Letak Lapang'],
    status: 'ready',
    favicon: '/assets/themes/minimalist/favicon.svg',
  },
  {
    id: 'islamic',
    name: 'Islamic Arabian Garden',
    category: 'islami',
    subtitle: 'Syar\'i & Sakral Kontemporer',
    description: 'Nuansa sakral islami berhias lengkungan kubah Arabesque, kaligrafi bismillah, dan taburan bintang geometris.',
    thumbnail: '/assets/themes/islamic/thumbnail.svg',
    previewColors: {
      primary: '#0F4C5C',
      secondary: '#C5A059',
      accent: '#E5C158',
      bg: '#FAF6EE',
    },
    features: ['Arabesque Arches', 'Bismillah Kaligrafi', 'Islamic 8-Star Rub el Hizb', 'Syar\'i & Sakral Kontemporer'],
    status: 'ready',
    favicon: '/assets/themes/islamic/favicon.svg',
  },
  {
    id: 'minang',
    name: 'Minangkabau Royal Songket',
    category: 'adat',
    subtitle: 'Baralek Gadang Adat Minang',
    description: 'Kemegahan ranah Minang berhias mahkota Suntiang emas bertingkat, Rumah Gadang gonjong, ukiran Pucuak Rebung, dan beludru marun.',
    thumbnail: '/assets/themes/minang/thumbnail.svg',
    previewColors: {
      primary: '#7B1122',
      secondary: '#D4AF37',
      accent: '#FFF3C4',
      bg: '#FAF5F0',
    },
    features: ['Mahkota Suntiang Emas', 'Rumah Gadang Gonjong', 'Songket Pucuak Rebung', 'Baralek Gadang Minang'],
    status: 'ready',
    favicon: '/assets/themes/minang/favicon.svg',
  },
  {
    id: 'bali',
    name: 'Balinese Royal Temple',
    category: 'adat',
    subtitle: 'Pawiwahan Adat Bali Agung',
    description: 'Kemegahan sakral adat Bali berhias Gapura Candi Bentar, payung kehormatan Tedung Agung, ukiran Patra Punggel, dan keharuman Bunga Jepun Kamboja.',
    thumbnail: '/assets/themes/bali/thumbnail.svg',
    previewColors: {
      primary: '#7C2D12',
      secondary: '#C5A059',
      accent: '#E5C158',
      bg: '#FAF6F0',
    },
    features: ['Gapura Candi Bentar', 'Bunga Jepun Melayang', 'Tedung Agung Emas', 'Patra Punggel Carvings'],
    status: 'ready',
    favicon: '/assets/themes/bali/favicon.svg',
  },
  {
    id: 'batak',
    name: 'Batak Toba Royal Gorga',
    category: 'adat',
    subtitle: 'Unjuk Adat Bolon Batak Toba',
    description: 'Kemegahan adat Batak Toba berhias ornamen ukiran Gorga sakral, motif tenun Ulos Ragidup/Sadum, siluet Ruma Bolon, dan palet Tolu Bolit merah-hitam-emas.',
    thumbnail: '/assets/themes/batak/thumbnail.svg',
    previewColors: {
      primary: '#7A1B1E',
      secondary: '#1C1917',
      accent: '#D4AF37',
      bg: '#FAF6F0',
    },
    features: ['Ukiran Seni Gorga', 'Motif Ulos Ragidup', 'Siluet Ruma Bolon', 'Horas Jala Gabe'],
    status: 'ready',
    favicon: '/assets/themes/batak/favicon.svg',
  },
  {
    id: 'bugis',
    name: 'Bugis-Makassar Royal Baju Bodo',
    category: 'adat',
    subtitle: 'Baruga Saoraja & Sutra Lipa Sabbe',
    description: 'Kemegahan adat Bugis-Makassar berhias ornamen wadah Bosara renda emas, siluet atap Saoraja/Bola Soba, corak sutra Lipa Sabbe, dan aksara Lontara sakral.',
    thumbnail: '/assets/themes/bugis/thumbnail.svg',
    previewColors: {
      primary: '#8B1E1E',
      secondary: '#C59B27',
      accent: '#D97706',
      bg: '#FAF6F0',
    },
    features: ['Wadah Bosara Emas', 'Atap Saoraja Bangsawan', 'Taburan Bente & Pandan', 'Aksara Lontara Salama'],
    status: 'ready',
    favicon: '/assets/themes/bugis/favicon.svg',
  },
  {
    id: 'palembang',
    name: 'Palembang Sriwijaya Songket Aesan Gede',
    category: 'adat',
    subtitle: 'Kemegahan Sriwijaya & Songket Lepus Emas',
    description: 'Kemegahan kerajaan Sriwijaya berhias ornamen Mahkota Kesuhun Aesan Gede bertingkat, Teratai Dada emas, atap Rumah Limas, dan kain Songket Lepus benang emas murni.',
    thumbnail: '/assets/themes/palembang/thumbnail.svg',
    previewColors: {
      primary: '#780016',
      secondary: '#D4AF37',
      accent: '#FFE082',
      bg: '#FAF5EE',
    },
    features: ['Mahkota Aesan Gede', 'Rumah Limas Simbar', 'Songket Lepus Emas', 'Bunga Cempaka Melati'],
    status: 'ready',
    favicon: '/assets/themes/palembang/favicon.svg',
  },
  {
    id: 'spotify',
    name: 'Spotify Interactive',
    category: 'modern',
    subtitle: 'Wedding Track & Love Playlist',
    description: 'Konsep viral pemutar musik Spotify dengan piringan hitam vinyl berputar, lencana Verified Newlyweds, dan album tracklist kisah cinta.',
    thumbnail: '/assets/themes/spotify/thumbnail.svg',
    previewColors: {
      primary: '#1DB954',
      secondary: '#181818',
      accent: '#1ED760',
      bg: '#121212',
    },
    features: ['Rotating Vinyl Cover', 'Verified Newlyweds', 'Album Tracklist', 'Floating Music Notes'],
    status: 'ready',
    favicon: '/assets/themes/spotify/favicon.svg',
  },
  {
    id: 'netflix',
    name: 'Netflix Premiere',
    category: 'modern',
    subtitle: 'Cinematic Wedding & Series',
    description: 'Konsep viral streaming sinematik Netflix dengan efek audio Ta-Dum!, episode Akad & Resepsi, rating 99% Match, serta profil bintang Cast & Crew.',
    thumbnail: '/assets/themes/netflix/thumbnail.svg',
    previewColors: {
      primary: '#E50914',
      secondary: '#141414',
      accent: '#FFFFFF',
      bg: '#0F0F0F',
    },
    features: ['Ta-Dum Sound Effect', 'Episode 1 & 2 Series', 'Cast & Crew Profile', 'Trending 99% Match'],
    status: 'ready',
    favicon: '/assets/themes/netflix/favicon.svg',
  },
  {
    id: 'apple',
    name: 'Apple iOS Bento Grid',
    category: 'modern',
    subtitle: 'Apple Ecosystem & Bento OS',
    description: 'Konsep modern viral iOS & Bento Grid dengan Dynamic Island interaktif, Face ID Lock Screen unlock audio, Apple Wallet gift cards, dan iMessage chat bubbles.',
    thumbnail: '/assets/themes/apple/thumbnail.svg',
    previewColors: {
      primary: '#007AFF',
      secondary: '#E5E5EA',
      accent: '#D4AF37',
      bg: '#F2F2F7',
    },
    features: ['Dynamic Island Widget', 'Lock Screen Unlock Chime', 'Bento Grid Layout', 'Apple Wallet Digital Gift'],
    status: 'ready',
    favicon: '/assets/themes/apple/favicon.svg',
  },
  {
    id: 'instagram',
    name: 'Instagram Stories & Reels',
    category: 'modern',
    subtitle: 'Wedding Stories & Close Friends',
    description: 'Konsep modern viral Instagram Stories berformat 9:16 vertikal imersif dengan progress bar tersegmentasi, stiker countdown live, RSVP polling, dan reaksi hati double-tap.',
    thumbnail: '/assets/themes/instagram/thumbnail.svg',
    previewColors: {
      primary: '#E1306C',
      secondary: '#FD1D1D',
      accent: '#FFD600',
      bg: '#000000',
    },
    features: ['Story Segmented Progress', 'Live Countdown Sticker', 'RSVP Poll Sticker', 'Double-Tap Floating Hearts'],
    status: 'ready',
    favicon: '/assets/themes/instagram/favicon.svg',
  },
  {
    id: 'vintage',
    name: 'Vintage Newspaper Gazette',
    category: 'modern',
    subtitle: 'The Wedding Gazette & Editorial Journal',
    description: 'Konsep koran cetak broadsheet klasik 1920-an berbalut kertas koran antik, masthead retro The Wedding Gazette, stempel pos berputar, dan audio mesin tik mekanik.',
    thumbnail: '/assets/themes/vintage/thumbnail.svg',
    previewColors: {
      primary: '#1E1E1E',
      secondary: '#8B3A2B',
      accent: '#B8860B',
      bg: '#F4EBD9',
    },
    features: ['Retro Masthead Gazette', 'Typewriter Sound Chime', 'Broadsheet Editorial Grid', 'Vintage Postal Stamp'],
    status: 'ready',
    favicon: '/assets/themes/vintage/favicon.svg',
  },
  {
    id: 'toraja',
    name: 'Toraja Tongkonan Heritage',
    category: 'adat',
    subtitle: 'Mahakarya Pa\'ssura & Kemegahan Tongkonan',
    description: 'Nuansa agung Tana Toraja berhias arsitektur atap perahu Tongkonan menjulang, ukiran sakral Pa\'tedong & Pa\'barre Allo, kalung manik Kandaure emas, dan melodi tiup Pa\'pompang.',
    thumbnail: '/assets/themes/toraja/thumbnail.svg',
    previewColors: {
      primary: '#8B1E19',
      secondary: '#E5A93C',
      accent: '#1A1A1A',
      bg: '#F7F2EB',
    },
    features: ['Tongkonan Curve Arch', 'Ukiran Pa\'tedong Emas', 'Manik Kandaure Filigree', 'Pa\'pompang Bamboo Sound'],
    status: 'ready',
    favicon: '/assets/themes/toraja/favicon.svg',
  },
  {
    id: 'arcade',
    name: '8-Bit Retro Arcade',
    category: 'modern',
    subtitle: 'Level 1 Passed: Press START to Marry',
    description: 'Nostalgia video game retro 8-bit/16-bit dengan antarmuka pixel art, dialog box RPG mempelai Player 1 & 2 Co-Op, HP/Love bar, dan suara sintetis chiptune.',
    thumbnail: '/assets/themes/arcade/thumbnail.svg',
    previewColors: {
      primary: '#22D3EE',
      secondary: '#F43F5E',
      accent: '#F59E0B',
      bg: '#0F172A',
    },
    features: ['Press START Cover', 'Chiptune 8-Bit Jingle', 'Co-Op Player 1 & 2 Stats', 'Pixel Heart Floating'],
    status: 'ready',
    favicon: '/assets/themes/arcade/favicon.svg',
  },
  {
    id: 'royal',
    name: 'Royal Decree & Wax Seal',
    category: 'modern',
    subtitle: 'Titah Kerajaan & Surat Gulung Perkamen',
    description: 'Kemegahan titah kerajaan abad pertengahan berhias gulungan perkamen antik, stempel segel lilin merah 3D, kaligrafi tinta emas, dan denting harpa magis.',
    thumbnail: '/assets/themes/royal/thumbnail.svg',
    previewColors: {
      primary: '#2C1810',
      secondary: '#854D0E',
      accent: '#D4AF37',
      bg: '#F5E6CA',
    },
    features: ['3D Melted Wax Seal', 'Royal Decree Scroll', 'Magic Harp Chime', 'Golden Stardust Particles'],
    status: 'ready',
    favicon: '/assets/themes/royal/favicon.svg',
  },
  {
    id: 'dayak',
    name: 'Dayak Kenyah Borneo',
    category: 'adat',
    subtitle: 'Pesona Talawang & Petikan Magis Sape\'',
    description: 'Kemegahan adat Dayak Kenyah Kalimantan berhias perisai sakral Talawang, bulu burung Enggang, sulur mistis Aso & Kalung Manik, serta petikan nada magis musik Sape\'.',
    thumbnail: '/assets/themes/dayak/thumbnail.svg',
    previewColors: {
      primary: '#8B0000',
      secondary: '#D4AF37',
      accent: '#F59E0B',
      bg: '#FBF8F2',
    },
    features: ['Perisai Sakral Talawang', 'Petikan Magis Sape\' Kenyah', 'Bulu Burung Enggang Melayang', 'Sulur Motif Aso Naga Borneo'],
    status: 'ready',
    favicon: '/assets/themes/dayak/favicon.svg',
  },
  {
    id: 'cyberpunk',
    name: 'Cyberpunk Neo-Jakarta',
    category: 'modern',
    subtitle: 'Matrimony in Night City: High-Tech Love',
    description: 'Gaya futuristik Cyberpunk 2077 berhias sirkuit neon cyan & magenta, HUD biometrik kuantum cinta, efek digital glitch dinamis, dan denting laser synth masa depan.',
    thumbnail: '/assets/themes/cyberpunk/thumbnail.svg',
    previewColors: {
      primary: '#00F0FF',
      secondary: '#FF007F',
      accent: '#FFE600',
      bg: '#0A0A12',
    },
    features: ['Cyberpunk Biometric HUD', 'Laser Synth Audio Glitch', 'Floating Neon Hex Particles', 'Digital Glitch Cyber Frame'],
    status: 'ready',
    favicon: '/assets/themes/cyberpunk/favicon.svg',
  },
  {
    id: 'aceh',
    name: 'Aceh Serambi Mekkah',
    category: 'adat',
    subtitle: 'Pinto Aceh & Rencong Meukuta Alam',
    description: 'Kemegahan adat Aceh berhias pintu gerbang Pinto Aceh geometris, ornamen Kupiah Meukeutop keemasan, sulur Awan Siweueh, dan petikan Seudati syahdu.',
    thumbnail: '/assets/themes/aceh/thumbnail.svg',
    previewColors: {
      primary: '#800000',
      secondary: '#D4AF37',
      accent: '#1A472A',
      bg: '#FAF6EE',
    },
    features: ['Gerbang Emas Pinto Aceh', 'Mahkota Kupiah Meukeutop', 'Sulur Awan Siweueh', 'Petikan Gambus & Seudati'],
    status: 'coming_soon',
    favicon: '/assets/themes/aceh/favicon.svg',
  },
  {
    id: 'banjar',
    name: 'Banjar Baamar Galung Pancar Matahari',
    category: 'adat',
    subtitle: 'Mahkota Kemilau Intan & Rumah Bubungan Tinggi',
    description: 'Keagungan adat Banjar Kalimantan Selatan berhias mahkota Baamar Galung keemasan, ronce melati bogam, kilau intan Martapura, dan arsitektur Rumah Bubungan Tinggi.',
    thumbnail: '/assets/themes/banjar/thumbnail.svg',
    previewColors: {
      primary: '#996515',
      secondary: '#F59E0B',
      accent: '#4A154B',
      bg: '#FFFDF7',
    },
    features: ['Mahkota Baamar Galung Emas', 'Ronce Melati Bogam', 'Rumah Adat Bubungan Tinggi', 'Gemerlap Intan Martapura'],
    status: 'coming_soon',
    favicon: '/assets/themes/banjar/favicon.svg',
  },
  {
    id: 'melayu',
    name: 'Melayu Riau Teluk Belanga',
    category: 'adat',
    subtitle: 'Tenun Songket Siak & Selembayung Lembayung Diraja',
    description: 'Kesantunan adat Melayu berhias songket tenun Siak bertabur benang emas, hiasan atap Selembayung, tepak sirih persembahan, dan pantun seloka berbalut kuning diraja.',
    thumbnail: '/assets/themes/melayu/thumbnail.svg',
    previewColors: {
      primary: '#EAB308',
      secondary: '#1E3A8A',
      accent: '#991B1B',
      bg: '#FCFBF7',
    },
    features: ['Ornamen Atap Selembayung', 'Tenun Songket Siak Diraja', 'Tepak Sirih Persembahan', 'Seloka Pantun Melayu'],
    status: 'coming_soon',
    favicon: '/assets/themes/melayu/favicon.svg',
  },
  {
    id: 'sasak',
    name: 'Sasak Lombok Bale Tani',
    category: 'adat',
    subtitle: 'Tenun Ikat Subahnale & Karisma Gunung Rinjani',
    description: 'Keindahan pulau seribu masjid berbalut kain tenun ikat Subahnale khas Sade, lumbung padi tradisional Bale Tani, dan siluet agung Gunung Rinjani Lombok.',
    thumbnail: '/assets/themes/sasak/thumbnail.svg',
    previewColors: {
      primary: '#854D0E',
      secondary: '#D97706',
      accent: '#065F46',
      bg: '#FDFBF7',
    },
    features: ['Tenun Songket Subahnale', 'Arsitektur Bale Tani Lumbung', 'Siluet Agung Rinjani', 'Gendang Beleq Rhythms'],
    status: 'coming_soon',
    favicon: '/assets/themes/sasak/favicon.svg',
  },
  {
    id: 'papua',
    name: 'Papua Cenderawasih Paradise',
    category: 'adat',
    subtitle: 'Kemilau Raja Ampat & Mahkota Burung Surga',
    description: 'Eksotisme bumi Cenderawasih berhias mahkota bulu burung surga, ukiran kayu Asmat magis, rajutan noken tradisional, dan gradasi pirus zamrud perairan Raja Ampat.',
    thumbnail: '/assets/themes/papua/thumbnail.svg',
    previewColors: {
      primary: '#78350F',
      secondary: '#F59E0B',
      accent: '#0EA5E9',
      bg: '#FAF7F2',
    },
    features: ['Mahkota Emas Cenderawasih', 'Ukiran Kayu Magis Asmat', 'Pirus Laut Raja Ampat', 'Rajutan Noken Tradisional'],
    status: 'coming_soon',
    favicon: '/assets/themes/papua/favicon.svg',
  },
  {
    id: 'cinema',
    name: 'IMAX Cinema Premiere & Movie Ticket',
    category: 'modern',
    subtitle: 'Now Showing: A Lifetime Romantic Blockbuster',
    description: 'Konsep sinematik karpet merah layaknya gala premiere film bioskop, dilengkapi tiket bioskop barcode robek, sorotan spotlight premiere, dan popcorn retro.',
    thumbnail: '/assets/themes/cinema/thumbnail.svg',
    previewColors: {
      primary: '#E11D48',
      secondary: '#F59E0B',
      accent: '#0F172A',
      bg: '#080A12',
    },
    features: ['Gala Premiere Ticket Stub', 'Hollywood Searchlight Sweep', 'Now Showing Film Slate', 'Cinema Dolby Surround Vibes'],
    status: 'coming_soon',
    favicon: '/assets/themes/cinema/favicon.svg',
  },
  {
    id: 'airline',
    name: 'First-Class Boarding Pass & Aviation',
    category: 'modern',
    subtitle: 'Flight Love-2026: Destination Forever Together',
    description: 'Antarmuka boarding pass maskapai penerbangan first-class dengan kode bandara penerbangan IATA, paspor stempel visa romantis, dan peta rute jelajah cinta mengitari awan.',
    thumbnail: '/assets/themes/airline/thumbnail.svg',
    previewColors: {
      primary: '#0284C7',
      secondary: '#E0E7FF',
      accent: '#F59E0B',
      bg: '#061626',
    },
    features: ['First Class Boarding Pass', 'Flight Radar Map Track', 'Passport Custom Visa Stamp', 'Seat 1A & 1B Love Reservation'],
    status: 'coming_soon',
    favicon: '/assets/themes/airline/favicon.svg',
  },
  {
    id: 'anime',
    name: 'Romantic Anime & Manga Panel',
    category: 'modern',
    subtitle: 'Kimi no Na wa Inspired Love Canvas',
    description: 'Estetika visual manga dan anime Jepang berhias kelopak bunga Sakura gugur perlahan, langit gradasi senja komet Makoto Shinkai, dan panel dialog manga romantis.',
    thumbnail: '/assets/themes/anime/thumbnail.svg',
    previewColors: {
      primary: '#EC4899',
      secondary: '#6366F1',
      accent: '#F43F5E',
      bg: '#1A0C24',
    },
    features: ['Falling Sakura Petals Shower', 'Manga Speech Panel Layout', 'Makoto Shinkai Twilight Sky', 'Lo-Fi Anime Chill Soundtrack'],
    status: 'coming_soon',
    favicon: '/assets/themes/anime/favicon.svg',
  },
  {
    id: 'glassmorphism',
    name: 'Glassmorphism Aurora Hologram',
    category: 'modern',
    subtitle: 'Frosted Glass & Iridescent Prism Light',
    description: 'Desain ultra-modern berhias lapisan frosted glass tembus pandang, pembiasan cahaya prisma pelangi aurora borealis, dan tipografi sans-serif futuristik bersih.',
    thumbnail: '/assets/themes/glassmorphism/thumbnail.svg',
    previewColors: {
      primary: '#8B5CF6',
      secondary: '#06B6D4',
      accent: '#EC4899',
      bg: '#0B0F19',
    },
    features: ['Frosted Glassmorphism Panels', 'Iridescent Hologram Prism', 'Dynamic Aurora Borealis Wave', 'Ultra Clean Neo-Modern UI'],
    status: 'coming_soon',
    favicon: '/assets/themes/glassmorphism/favicon.svg',
  },
  {
    id: 'synthwave',
    name: 'Retro 80s Synthwave & Neon Sunset',
    category: 'modern',
    subtitle: 'Outrun Wireframe Grid & Electric Miami Sunset',
    description: 'Nuansa retro futurisme era 80-an dengan horizon wireframe perspektif 3D, matahari terbenam neon bergaris horizontal, pohon palem neon, dan lantunan synthwave analog.',
    thumbnail: '/assets/themes/synthwave/thumbnail.svg',
    previewColors: {
      primary: '#F43F5E',
      secondary: '#8B5CF6',
      accent: '#FBBF24',
      bg: '#070210',
    },
    features: ['Perspective 3D Outrun Grid', 'Striped Neon Sunset Sun', 'Retro Synth Analog Arpeggio', 'Neon Glow Palm Silhouettes'],
    status: 'coming_soon',
    favicon: '/assets/themes/synthwave/favicon.svg',
  },
  {
    id: 'ottoman',
    name: 'Ottoman Empire Istanbul Grandeur',
    category: 'islami',
    subtitle: 'Kemegahan Istana Topkapi & Kubah Hagia Sophia',
    description: 'Keagungan kekhalifahan Utsmaniyah berhias motif keramik Iznik biru pirus legendaris, kaligrafi Thuluth emas, kubah megah Hagia Sophia, dan ornamen bulan sabit kembar.',
    thumbnail: '/assets/themes/ottoman/thumbnail.svg',
    previewColors: {
      primary: '#0E7490',
      secondary: '#B45309',
      accent: '#881337',
      bg: '#041B24',
    },
    features: ['Keramik Biru Iznik Ottoman', 'Kubah Megah Hagia Sophia', 'Kaligrafi Thuluth Berlapis Emas', 'Ornamen Sabit Kembar Diraja'],
    status: 'coming_soon',
    favicon: '/assets/themes/ottoman/favicon.svg',
  },
  {
    id: 'moroccan',
    name: 'Moroccan Riad & Zellige Mosaic',
    category: 'islami',
    subtitle: 'Mozaik Geometris Maroko & Lentera Khas Marrakech',
    description: 'Kemolekan arsitektur Riad Marrakech berhias lantai mozaik geometris Zellige terakota, lengkungan tapal kuda Moorish, lentera tembaga berukir, dan aroma mawar Sahara.',
    thumbnail: '/assets/themes/moroccan/thumbnail.svg',
    previewColors: {
      primary: '#C2410C',
      secondary: '#0284C7',
      accent: '#D97706',
      bg: '#1F0A02',
    },
    features: ['Mozaik Keramik Zellige 8-Lipat', 'Lengkungan Tapal Kuda Moorish', 'Lentera Tembaga Marrakech', 'Nuansa Eksotis Riad Courtyard'],
    status: 'coming_soon',
    favicon: '/assets/themes/moroccan/favicon.svg',
  },
  {
    id: 'andalusia',
    name: 'Al-Andalus Granada Alhambra',
    category: 'islami',
    subtitle: 'Pancuran Air Taman Generalife & Muqarnas Granada',
    description: 'Keanggunan masa keemasan Islam di Spanyol berhias relief langit-langit sarang lebah Muqarnas, air mancur marmer Generalife Alhambra, dan rimbun pohon zaitun berkilau zamrud.',
    thumbnail: '/assets/themes/andalusia/thumbnail.svg',
    previewColors: {
      primary: '#047857',
      secondary: '#D4AF37',
      accent: '#B91C1C',
      bg: '#021810',
    },
    features: ['Relief Plafon Sarang Lebah Muqarnas', 'Pancuran Taman Air Generalife', 'Motif Daun Zaitun Keemasan', 'Harmoni Klasik Andalusia'],
    status: 'coming_soon',
    favicon: '/assets/themes/andalusia/favicon.svg',
  },
  {
    id: 'nabawi',
    name: 'Madinah Nabawi Serenity',
    category: 'islami',
    subtitle: 'Payung Raksasa Mekar & Kubah Hijau Kedamaian',
    description: 'Ketenteraman kota suci Madinah Al-Munawwarah berhias siluet Kubah Hijau (Green Dome), pilar marmer putih berbalut emas, dan payung hidrolik raksasa yang mekar anggun.',
    thumbnail: '/assets/themes/nabawi/thumbnail.svg',
    previewColors: {
      primary: '#15803D',
      secondary: '#CA8A04',
      accent: '#0284C7',
      bg: '#021F11',
    },
    features: ['Payung Raksasa Nabawi Mekar', 'Kubah Hijau As-Salam Madinah', 'Pilar Marmer Putih Rawdah', 'Lantunan Doa & Salawat Syahdu'],
    status: 'coming_soon',
    favicon: '/assets/themes/nabawi/favicon.svg',
  },
];


