import { ThemeMeta } from './types';

export const THEME_CATALOG: ThemeMeta[] = [
  {
    id: 'betawi',
    name: 'Betawi Heritage',
    category: 'adat',
    subtitle: 'Adat Betawi Klasik Modern',
    description: 'Nuansa hangat adat Betawi berhias ornamen Gigi Balang, Ondel-ondel siluet elegan, dan arsitektur Rumah Kebaya.',
    thumbnail: '/assets/themes/betawi/thumbnail.jpg',
    previewColors: {
      primary: '#5B7065',
      secondary: '#B85D43',
      accent: '#D4AF37',
      bg: '#E8EBE3',
    },
    features: ['Gigi Balang Frame', 'Ondel-ondel Siluet', 'Bunga Flora Melayang', 'Musik Mengambang'],
    status: 'ready',
    favicon: '/assets/themes/betawi/favicon.svg',
  },
  {
    id: 'jawa',
    name: 'Javanese Royal Kraton',
    category: 'adat',
    subtitle: 'Adat Jawa Klasik Ningrat',
    description: 'Kemegahan ningrat keraton Jawa dengan ornamen sakral Gunungan Wayang Kulit, batik Parang, dan aksen emas keemasan.',
    thumbnail: '/assets/themes/jawa/thumbnail.svg',
    previewColors: {
      primary: '#1B3B2B',
      secondary: '#C5A059',
      accent: '#E5C158',
      bg: '#FAF8F2',
    },
    features: ['Gunungan Wayang Mas', 'Serat Ulem Pawiwahan', 'Bingkai Ukiran Keraton', 'Batik Royal Gold'],
    status: 'ready',
    favicon: '/assets/themes/jawa/favicon.svg',
  },
  {
    id: 'sunda',
    name: 'Sundanese Parahyangan',
    category: 'adat',
    subtitle: 'Adat Sunda Asri & Suci',
    description: 'Keanggunan mahkota Siger Sunda, ronce melati putih, motif Priangan, dan nuansa alam Parahyangan yang sejuk.',
    thumbnail: '/assets/themes/sunda/thumbnail.svg',
    previewColors: {
      primary: '#4A6B5D',
      secondary: '#E6D5B8',
      accent: '#D4AF37',
      bg: '#F4F7F4',
    },
    features: ['Mahkota Siger Sunda', 'Serat Ulem Pawiwahan', 'Ronce Melati Putih', 'Bambu Priangan Arch'],
    status: 'ready',
    favicon: '/assets/themes/sunda/favicon.svg',
  },
  {
    id: 'minimalist',
    name: 'Modern Botanical Minimalist',
    category: 'modern',
    subtitle: 'Nasional & Intimate Wedding',
    description: 'Gaya modern minimalis berbalut tipografi serif bersih, dedaunan eucalyptus cat air, dan tata letak lapang tanpa sekat.',
    thumbnail: '/assets/themes/minimalist/thumbnail.svg',
    previewColors: {
      primary: '#2D3748',
      secondary: '#9AA79C',
      accent: '#D4AF37',
      bg: '#F7FAFC',
    },
    features: ['Clean Aesthetic Serif', 'Eucalyptus Watercolor', 'Editorial Minimalist', 'Tata Letak Lapang'],
    status: 'ready',
    favicon: '/assets/themes/minimalist/favicon.svg',
  },
  {
    id: 'islamic',
    name: 'Islamic Arabian Garden',
    category: 'islami',
    subtitle: 'Syar\'i & Sakral Kontemporer',
    description: 'Nuansa sakral islami berhias lengkungan kubah Arabesque, kaligrafi bismillah, dan taburan bintang geometris.',
    thumbnail: '/assets/themes/islamic/thumbnail.svg',
    previewColors: {
      primary: '#0F4C5C',
      secondary: '#C5A059',
      accent: '#E5C158',
      bg: '#FAF6EE',
    },
    features: ['Arabesque Arches', 'Bismillah Kaligrafi', 'Islamic 8-Star Rub el Hizb', 'Syar\'i & Sakral Kontemporer'],
    status: 'ready',
    favicon: '/assets/themes/islamic/favicon.svg',
  },
  {
    id: 'minang',
    name: 'Minangkabau Royal Songket',
    category: 'adat',
    subtitle: 'Baralek Gadang Adat Minang',
    description: 'Kemegahan ranah Minang berhias mahkota Suntiang emas bertingkat, Rumah Gadang gonjong, ukiran Pucuak Rebung, dan beludru marun.',
    thumbnail: '/assets/themes/minang/thumbnail.svg',
    previewColors: {
      primary: '#7B1122',
      secondary: '#D4AF37',
      accent: '#FFF3C4',
      bg: '#FAF5F0',
    },
    features: ['Mahkota Suntiang Emas', 'Rumah Gadang Gonjong', 'Songket Pucuak Rebung', 'Baralek Gadang Minang'],
    status: 'ready',
    favicon: '/assets/themes/minang/favicon.svg',
  },
  {
    id: 'bali',
    name: 'Balinese Royal Temple',
    category: 'adat',
    subtitle: 'Pawiwahan Adat Bali Agung',
    description: 'Kemegahan sakral adat Bali berhias Gapura Candi Bentar, payung kehormatan Tedung Agung, ukiran Patra Punggel, dan keharuman Bunga Jepun Kamboja.',
    thumbnail: '/assets/themes/bali/thumbnail.svg',
    previewColors: {
      primary: '#7C2D12',
      secondary: '#C5A059',
      accent: '#E5C158',
      bg: '#FAF6F0',
    },
    features: ['Gapura Candi Bentar', 'Bunga Jepun Melayang', 'Tedung Agung Emas', 'Patra Punggel Carvings'],
    status: 'ready',
    favicon: '/assets/themes/bali/favicon.svg',
  },
];
